# This workflow will run web tests with Docker
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: ATSD Web Tests in Docker container

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-pull:
    container: axibase/atsd-web-test
    runs-on: ubuntu-latest
    steps: 
      - run: echo "Test completed"
   
